Feature/oed interface [WIP]
OasisLMF/ODS_OpenExposureData pull request #89
Opened 2022-10-27 17:47 UTC by sstruzik

Reworking of ods tools to merge all functionality into one consistent interface

2022-12-06 11:47 UTC, sambles commented
Note: add pandas as package requirement

2022-12-06 11:54 UTC, sambles commented
Add package requirements for:
```
pandas 
chardet 
```
```

2022-12-09 10:37 UTC, mtazzari commented
@sambles in your review, can you please check the GH actions workflows? You're more familiar with them. Thanks!

2022-12-09 10:43 UTC, sambles commented
> @sambles in your review, can you please check the GH actions workflows? You're more familiar with them. Thanks!

@mtazzari I merge an update on the ODS testing side already https://github.com/OasisLMF/ODS_OpenExposureData/pull/95 , just looking at the oasislmf at the moment

2022-12-09 11:26 UTC, mtazzari commented on docker/extract_spec.py
> +    Args:
```suggestion

    Args:
```

2022-12-09 15:56 UTC, sambles reviewed
Issue running the following: 

ods_tools (https://github.com/OasisLMF/ODS_OpenExposureData/pull/108)
oasislmf (https://github.com/OasisLMF/OasisLMF/pull/1171) 
OasisPlatform (latest) 
PiWind (develop)

[platform_ods_interface_run-error.txt](https://github.com/OasisLMF/ODS_OpenExposureData/files/10196202/platform_ods_interface_run-error.txt)

2022-12-12 11:12 UTC, mtazzari requested changes
Very general comment is why we don't we have `ods_tools` in a separate repository instead of having it inside ODS_OpenExposureData.

A second comment is that I would rename `src` into `ods_tools`. `src` is C/C++ style legacy, and very generic. It'd be just neater to have it `ods_tools`.
 
Specific comments:
- I haven't tested/evaluated the design patterns you adopted here, so I cannot advise whether it would have been better to take different approach for the use cases. I'm not familiar enough with the typical usage, so I trust this was the best way to implement the functionality.
- docstrings: can you please do an overhaul of the docstrings throughout the code and amend them so that they follow the format we've agreed upon? See e.g. my suggestions in `docker/extract_spec.py` and in src/oed/exposure.py`. I've found docstrings that are about right, but many of them are either missing a description (eg src/oed/schema OedSchema.is_valid_vaue), or the input types, etc. I have commented on many but not all the docstrings that need to be fixed, please do check them all.
- please check throughout the code some typos: occupency -> occupancy, unkown -> unknown. I've fixed those that I could see but it's better to do a full text search with an IDE and catch all the occurrences. 
- there's a filename renaming: `src/tests/__init__.py` -> `src/data/.gitkeep`   is it correct?
- I find it confusing to have a mixture of "OED", "oed", "Oed" throughout code and documentation. Can we reduce the representations? Eg use OED consistently throughout code and documentation? and perhaps `oed` only for command line arguments?

To speed things up on your side, I've added many suggestions to the review, which you can accept or reject with just a click, then when you've passed all the suggestions, you can pull the code locally and do the other changes.

2022-12-13 15:07 UTC, sstruzik commented on docker/extract_spec.py
> +
done

2022-12-13 15:10 UTC, sstruzik commented on docker/extract_spec.py
> +        occupency_df
done

2022-12-13 15:11 UTC, sstruzik commented on src/README.md
> +```
after discussion dataframe vs df was equivalent so we keep the existing solution dataframe

2022-12-13 15:11 UTC, sstruzik commented on src/main.py
> +there is several option to specify the exposure data,
done

2022-12-13 15:12 UTC, sstruzik commented on src/main.py
> + if both are specified the specific path will overwrite the eventual source found looking in oed_dir.
should be better now

2022-12-13 15:14 UTC, sstruzik commented on docker/extract_spec.py
> +        ods_fields_df: OED Input Fields sheet as a Dataframe
done

2022-12-13 15:14 UTC, sstruzik commented on docker/extract_spec.py
> +        dict with info on perils and mapping between peril and list of sub perils
done

2022-12-13 17:23 UTC, sambles approved these changes

2022-12-15 15:09 UTC, merged